version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    ignore:
      - "black"
      - "furo"
      - "isort"
      - "pre-commit"
      - "pyright"
      - "pytest_image_diff"
      - "pytest-cov"
      - "pytest"
      - "reportlab"
      - "sphinx_design"
      - "svglib"
      - "sybil"
  - package-ecosystem: "pip"
    directory: "/"
    versioning-strategy: "increase"
    commit-message:
      prefix: "[dev]"
    schedule:
      interval: "weekly"
    allow:
      - "black"
      - "furo"
      - "isort"
      - "pre-commit"
      - "pyright"
      - "pytest_image_diff"
      - "pytest-cov"
      - "pytest"
      - "reportlab"
      - "sphinx_design"
      - "svglib"
      - "sybil"
