version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      dev:
        patterns:
          - "beautifulsoup4"
          - "furo"
          - "myst-parser"
          - "pyright"
          - "pytest_image_diff"
          - "pytest-cov"
          - "pytest-regressions"
          - "pytest"
          - "reportlab"
          - "sphinx_design"
          - "svglib"
          - "sybil"
      style:
        patterns:
          - "black"
          - "isort"
          - "pre-commit"
